### ISSUE TITLE
Component names with space

### ISSUE THREAD

**Issue by renjfk** [retejs/stage0-render-plugin#6]
I gave this a shot however didn't work since my components have space(s) in names. I would suggest using a class name transformer just like alight plugin had as following:

```javascript
function toClassName(str) {
    return str.toLowerCase().replace(/ /g, '-')
}
```

**Comment by trsh** [comment]
Can u drop a codepen example of what is not working? Didn't get it.

**Comment by renjfk** [comment]
Well I switched to react render and unfortunately don't have time to reproduce issue but just as a hint you can take a look at here https://github.com/retejs/react-render-plugin/blob/master/src/utils.js and maybe ask author why was this implemented in the first place.
